apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes_understanding
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: kubernetes_understanding
  template:
    metadata:
      labels:
        app: kubernetes_understanding
    spec:
      containers:
      - name: kubernetes_understanding
        image: kubernetes_understanding:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes_understanding
spec:
  selector:
    app: kubernetes_understanding
  ports:
  - port: 8080
    targetPort: 5000